### ISSUE TITLE
Feature request: apply generic label to all provisioned nodes?

### ISSUE THREAD

**Issue by vdice** [spinkube/runtime-class-manager#113]
In the current kwasm-operator project that this runtime-class-manager is derived from, a label is applied to each node that kwasm has successfully installed wasm shim(s) onto, eg `kwasm.sh/kwasm-provisioned=aks-apps-21730664-vmss000001` (ref https://github.com/KWasm/kwasm-operator/blob/main/controllers/provisioner_controller.go#L99).

In this project, I'm wondering if we might also entertain applying a generic label either in addition or instead, eg `some-appropriate-key=some-appropriate-value`, where `some-appropriate-value` is not specific to the node being labeled.

The main use case here is to enable easy scheduling of SpinApp resources to only the nodes provisioned with the shim by the runtime-class-manager via the configured RuntimeClass.  For example, the RuntimeClass could look like:

```yaml
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-spin-v2
handler: spin
scheduling:
  nodeSelector:
    some-appropriate-key: some-appropriate-value
```

Hence, to accomplish this goal, the label value would need to be generic and not a specific node name.

As a workaround and perhaps for many cases, operators can manually label the nodes that they will then annotate for installing the shim (via kwasm or soon runtime-class-manager) and can use such label(s) in the RuntimeClass config.  However, it could be nice if runtime-class-manager adds a label upon provisioning such that separate manual configuration of node(s) isn't strictly necessary.

**Comment by voigt** [comment]
Hey @vdice,

Thank you for creating an issue.

The way how runtime-class-manager currently handles node labeling:

Lets assume we have the following shim resource:

```yaml
apiVersion: runtime.kwasm.sh/v1alpha1 
kind: Shim
metadata:
  name: spin-v2
[...]
spec:
  nodeSelector:
    spin: "true"

  fetchStrategy:
    type: annonymousHttp
    anonHttp:
      location: "https://github.com/spinkube/containerd-shim-spin/releases/download/v0.14.1/containerd-shim-spin-v2-linux-aarch64.tar.gz"

  runtimeClass:
    name: spin-v2
    handler: spin

  rolloutStrategy:
    type: recreate

```

This will install the shim on all nodes with the label `spin=true`. Thus, the user is in total control of naming the selector.

In addition to this, rcm will create a dedicated label `<shim-name>=<status>` to reflect the deployment status of the shim. So, in our case, after successful shim installation, the node will get a label `spin-v2=provisioned`.

Possible states are:

* `provisioned`
* `pending`
* `failed`

Example:

```bash
kubectl get nodes --show-labels
NAME                  STATUS   ROLES           AGE   VERSION   LABELS
kwasm-control-plane   Ready    control-plane   68m   v1.29.2   beta.kubernetes.io/arch=arm64,beta.kubernetes.io/os=linux,kubernetes.io/arch=arm64,kubernetes.io/hostname=kwasm-control-plane,kubernetes.io/os=linux,node-role.kubernetes.io/control-plane=,node.kubernetes.io/exclude-from-external-load-balancers=
kwasm-worker          Ready    <none>          68m   v1.29.2   beta.kubernetes.io/arch=arm64,beta.kubernetes.io/os=linux,kubernetes.io/arch=arm64,kubernetes.io/hostname=kwasm-worker,kubernetes.io/os=linux,spin-v2=provisioned,spin=true

In this example, the SpinApp needs to be scheduled on nodes with `spin-v2=provisioned` and `spin=true`.

Does this fulfill your requirements?
