### ISSUE TITLE
node-installer distribution compatibility

### ISSUE THREAD

**Issue by phyrog** [spinkube/runtime-class-manager#65]
This is a tracking issue for testing compatibility of the go rewrite with the different K8s distributions supported by the installer shell script.

Untested:
- Rancher RKE2
- Azure AKS
- GCP GKE (Ubuntu nodes)
- AWS EKS (AmazonLinux2 nodes)
- AWS EKS (Ubuntu nodes)
- Digital Ocean Kubernetes

Works:
- Kind (with default settings)
- MiniKube (with default settings)

Works partially:
- MicroK8s (with overridden containerd config path): containerd restart does not work

Does not work:
- ...

**Comment by toksikk** [comment]
Can you elaborate a bit on your testing methodology so that we can evaluate whether it is appropriate for documentation in CONTRIBUTIONS.md? -> https://github.com/spinkube/runtime-class-manager/issues/49

**Comment by toksikk** [comment]
This is the manifest used for testing.

```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rcm-initializer
  labels:
    app: default-init
spec:
  selector:
    matchLabels:
      app: default-init
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rcm-initializer
        app: default-init
    spec:
      hostPID: true
      volumes:
        - name: node-root
          hostPath:
            path: /
        - name: assets
          emptyDir: {}
      initContainers:
        - image: busybox:latest
          name: shim-downloader
          env:
          volumeMounts:
            - name: assets
              mountPath: /assets
          command: ["/bin/sh", "-c"]
          args:
            - |
              wget -O- https://github.com/spinkube/containerd-shim-spin/releases/download/v0.13.0/containerd-shim-spin-v2-linux-$(uname -m).tar.gz  | tar -xzf - -C /assets;
        - image: ghcr.io/spinkube/node-installer:latest-feat-build-installer-image
          name: rcm-initializer
          imagePullPolicy: Always
          args:
            - "install"
            - "-H"
            - "/mnt/node-root"
          securityContext:
            privileged: true
          volumeMounts:
            - name: assets
              mountPath: /assets
            - name: node-root
              mountPath: /mnt/node-root/
      containers:
        - image: k8s.gcr.io/pause:3.1
          name: pause
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: spin-v2
handler: spin-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-spin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-spin
  template:
    metadata:
      labels:
        app: wasm-spin
    spec:
      runtimeClassName: spin-v2
      containers:
      - name: spin-hello
        image: ghcr.io/deislabs/containerd-wasm-shims/examples/spin-rust-hello:latest
        command: ["/"]
```
